### ISSUE TITLE
localtime 함수 조사

### ISSUE THREAD

**Issue by clover7kso** [clover7kso/OSS_File_Comparing_Program#18]
localtime 함수 조사

**Comment by clover7kso** [comment]
stat() 함수를 이용하면 파일의 상태를 알아올수 있다. 첫번째 인자로 주어진 file_name 의 상태를 얻어와서 두번째 인자인 buf 에 채워 넣는다.

lstat() 함수는 심볼릭:::링크(:12)파일의 원본파일의 상태를 얻어온다는 것을 제외하고는 stat() 함수와 동일하다.

fstat() 는 open(2) 등을 통해서 만들어진 파일지시자를 인자로 받아들인다는 점 외에는 stat() 와 동일한 일을 수행한다.

이들 함수는 성공적으로 수행될경우 파일의 정보를 stat구조체에 복사한다. stat구조체는 다음과 같이 정의되어 있다.

**Comment by clover7kso** [comment]
struct stat {
    dev_t         st_dev;      /* device */
    ino_t         st_ino;      /* inode */
    mode_t        st_mode;     /* protection */
    nlink_t       st_nlink;    /* number of hard links */
    uid_t         st_uid;      /* user ID of owner */
    gid_t         st_gid;      /* group ID of owner */
    dev_t         st_rdev;     /* device type (if inode device) */
    off_t         st_size;     /* total size, in bytes */
    blksize_t     st_blksize;  /* blocksize for filesystem I/O */
    blkcnt_t      st_blocks;   /* number of blocks allocated */
    time_t        st_atime;    /* time of last access */
    time_t        st_mtime;    /* time of last modification */
    time_t        st_ctime;    /* time of last change */
};

**Comment by clover7kso** [comment]
time_t 값을 이용하여 지역 시간을 기준으로 tm 구조체를 초기화한다. 
timer 가 가리키는 time_t 형 변수의 값을 이용하여 tm 구조체의 멤버들을 초기화 한 뒤 이를 가리키는 포인터를 리턴한다. 
참고적으로 현재 시간을 구해와야 하는 경우 십중 팔구 이 함수를 사용하게 된다. 

출처: http://itguru.tistory.com/120 [Programming IT]

**Comment by clover7kso** [comment]
time_t rawtime;
struct tm * timeinfo;

time ( &rawtime );
timeinfo = localtime ( &rawtime );

출처: http://itguru.tistory.com/120 [Programming IT]

**Comment by shin4523** [comment]
현재 시간을 구해와야하는 경우의 쓰이는 함수가 저희가 쓴 것말고 정말 없나요???

**Comment by quietash9704** [comment]
time _t값을 활용하여 localtime을 구할 수 있다는 부분 잘 알았습니다.
